repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      # Linter: catches errors and fixes simple ones
      - id: ruff
        args: [ --fix ]
      # Formatter: ensures consistent code style (the Black replacement)
      - id: ruff-format